### ISSUE TITLE
could we add some badge for Premium members in slack?

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/AgileVentures#18]
this from @mattlindsey - could we somehow mark premium members as premium in the AV slack?

**Comment by tansaku** [comment]
@mattlindsey - had this from slack:

> Hey there Sam,

> I'm afraid this isn't possible right now, apologies. That being said, this is a very cool idea and one that I'd actually love to see added myself.

> I'll happily pass on your suggestion to our product team for them to take into consideration in a future release. We're always looking for ways to improve so any and all feedback is greatly appreciated.

> All the best,

> Mark

**Comment by mattlindsey** [comment]
Badge added in the form of a 'status' icon.

**Comment by tansaku** [comment]
@mattlindsey it's a great improvement @mattlindsey - although I'd still really like to see the word premium in the badge to make it clearer to others what it actually was ...
