### ISSUE TITLE
"Starter pack"for new projects

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/AgileVentures#6]
<a href="https://github.com/freeranger"><img src="https://avatars.githubusercontent.com/u/1401069?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [freeranger](https://github.com/freeranger)**
_Friday Feb 26, 2016 at 10:11 GMT_
_Originally opened as https://github.com/AgileVentures/WebsiteOne/issues/843_

---

As the author of a new project
In order to get up and running quickly
I would like a "starter pack" of materials to be available:

Rationale:
Starting a new project is time consuming and broadly similar regardless of the project:
- Set up a repo
- Set up a PM tool (unless you want to stick with github issues)
- Set up a slack channel
- Document the getting started process.

It would be very useful if we had a set of standard recommended steps and recommended initial documentation.
In this PR https://github.com/AgileVentures/WebsiteOne/pull/830#issuecomment-189158060 for example there is a lot of good stuff that could easily apply to any project around the github workflow.
And I have seen broadly similar instructions across multiple projects about how to go from zero to building the project and seeing the tests pass.
I think it would be relatively easy to provide some starter docs that the PM can just copy and customise as required, together with some instructions on "this is where to go/who to contact to get a slack channel created", "if you want to use PT then talk to xxx" etc, and some recommendations such as "use the github repo itself rather than github wiki for documentation" etc...

**Comment by weedySeaDragon** [comment]
In addition to the technical infrastructure, there should be some skeleton **project** documentation in the "starter pack".
This is important for any project, but is even more important with AV:
- many people are novices and may have not have ever worked on a project
- project management skills are different than development skills (although Agile helps), so folks may not know the importance of having the project brief, etc.
  - even for folks that do have experience, they may not want to spend their energy on creating the docs.  Providing them with some default docs ensures at least _something_ is there
- AV projects have a high rate of churn (people churn), so it's critical to have clear info for onboarding
  - the content is important for folks new to (or considering) a project (What is this project about? how do I join? what tools/technologies are being used?)
- having a standard set of documents for each project means that people new to the site will be able to quickly learn what they want to know about a project.  (If a project chooses to do something different with the docs, that's obviously A-OK. But if 80% of the projects always have a page about joining a project in the same place in their project section on AV, that will make browsing the site/projects much easier.)


Some to include in the minimum set:
- project overview/brief (description, goals, stakeholders, priorities, constraints; all *short* in this doc)
- roles on the project (client interface, scrum-master, who approves PRs, etc.)
- onboarding: how to join this project
- workflow and processes for this project (how things happen/get done here. )
- README.md and CONTRIBUTING.md in the github repo

Much of this info exists for some projects. Would be straightforward to get the content together.

In addition to generating the starter project documents, some starter organization (what document files go where -- in the repo, on the project pages in AV?) would be helpful.

Compared to setting up the technical infrastructure, this is easy once there's some agreement on the content (not too hard with this AV, I think).  It would be just like generating stuff from templates.

**Comment by weedySeaDragon** [comment]
related? [EPIC] WSO: Project improvements: #https://github.com/AgileVentures/WebsiteOne/issues/1089
