### ISSUE TITLE
To Squash commits or not to Squash

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/AgileVentures#7]
We started discussing squashing commits in the WebSiteOne kick off yesterday.  Many OS projects require PRs to have their commits all squashed into one.  So far I don't think many AV projects have been squashing.  I've specifically avoided it on LocalSupport to try and make the complete history of the project available.

@freeranger and I have been discussing it a little in https://github.com/AgileVentures/WebsiteOne/pull/848 and here's a list of the pros and cons:
## Pros
- commit history is cleaner and easier to read and/or make sense of
- every commit is "green" and so tools like `git bisect` can be used, and any commit can be deployed with confidence?
- a lot of OS projects require it and so it's a great "advanced git" skill to get good at
## Cons
- It can be messy and complicated even for experienced git users
- We lose detailed history and the ability to cherry pick components
- It makes PR comment threads less readable if same branch/PR is used ...
- paired PRs may lead to a loss of commits for some individuals
## Summary

It seems clear that if a project is trying to onboard a lot of developers who are not so confident with git then requiring squashing (using git rebase) is going to be an extra barrier for those developers.  The project maintainers could conceivably take on the burden of doing the squashes for others, but that's a lot of work.   There are some notable advantages of squashing, but it seems like project maintainers should exercise caution before requiring them.

The question becomes should we trial them in a non-novice project such as WSO?  I am not sure ... I guess we could try and see if we like them or not ... do it on a case by case basis?  I can see in @freeranger 's rspec pull request there are also extremes between squashing one or two commits that are red and squashing them all.  So many options! :-)
## Related Reading
- http://jamescooke.info/git-to-squash-or-not-to-squash.html
- http://programmers.stackexchange.com/questions/263164/why-squash-git-commits-for-pull-requests

**Comment by freeranger** [comment]
If you want so roll all the commits up into one, would a simpler solution be, once you are ready to do a PR
- Pull in all upstream develop changes into your foo branch to get it bang up to date
- Create a brand new branch from upstream develop foo_release
- file system copy all the files from foo into foo_release
- Submit your PR from foo_release

That way you don't have all the shenanigans of git rebase etc going on, and yes you have lost all the history (though the committer can keep their foo branch if they wish) but this is one logical commit for a PR addressing an issue (hopefully already at the "right" size for a single piece of work) so in theory you only want all or nothing anyway....

**Comment by tansaku** [comment]
@freeranger see this video of @diraulo and I just sorting out a rebase: https://youtu.be/kL29P8ZBoa4?t=946

**Comment by pachonk** [comment]
> every commit is "green" and so tools like git bisect can be used, and any commit can be deployed with confidence?

This is my favorite reason

**Comment by dchudz** [comment]
In case it's relevant to you all... I just wrote this: www.davidchudzicki.com/posts/first-parent/. The `--first-parent` option can give you the best of both worlds between squashing and no-squashing.
